## Упражнение № 1
Создайте Series из каждого из элементов: списка, ndarray и словаря.

In [1]:
import pandas as pd
import numpy as np

mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

series_from_list = pd.Series(mylist)
print("Series из списка:")
print(series_from_list)

Series из списка:
0     a
1     b
2     c
3     e
4     d
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object


In [2]:
series_from_ndarray = pd.Series(myarr)
print("\nSeries из ndarray:")
print(series_from_ndarray)


Series из ndarray:
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
17    17
18    18
19    19
20    20
21    21
22    22
23    23
24    24
25    25
dtype: int32


In [3]:
series_from_dict = pd.Series(mydict)
print("\nSeries из словаря:")
print(series_from_dict)


Series из словаря:
a     0
b     1
c     2
e     3
d     4
f     5
g     6
h     7
i     8
j     9
k    10
l    11
m    12
n    13
o    14
p    15
q    16
r    17
s    18
t    19
u    20
v    21
w    22
x    23
y    24
z    25
dtype: int32


## Упражнение № 2
Преобразуйте `ser` в датафрейм с его индексом в качестве еще одного столбца датафрейма.

In [4]:
import pandas as pd
import numpy as np

mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)

df = ser.reset_index()
df.columns = ['index', 'value']

print(df)

   index  value
0      a      0
1      b      1
2      c      2
3      e      3
4      d      4
5      f      5
6      g      6
7      h      7
8      i      8
9      j      9
10     k     10
11     l     11
12     m     12
13     n     13
14     o     14
15     p     15
16     q     16
17     r     17
18     s     18
19     t     19
20     u     20
21     v     21
22     w     22
23     x     23
24     y     24
25     z     25


## Упражнение № 3
Объедините `ser1` и `ser2`, чтобы сформировать датафрейм.

In [5]:
import pandas as pd
import numpy as np

mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

ser1 = pd.Series(mylist)
ser2 = pd.Series(myarr)

df = pd.DataFrame({'col1': ser1, 'col2': ser2})

print(df)

   col1  col2
0     a     0
1     b     1
2     c     2
3     e     3
4     d     4
5     f     5
6     g     6
7     h     7
8     i     8
9     j     9
10    k    10
11    l    11
12    m    12
13    n    13
14    o    14
15    p    15
16    q    16
17    r    17
18    s    18
19    t    19
20    u    20
21    v    21
22    w    22
23    x    23
24    y    24
25    z    25


## Упражнение № 4
Добавьте имя ряда  `ser`, назвав его `latin_letters`.

In [6]:
import pandas as pd

ser = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser.name = 'latin_letters'
df = pd.DataFrame({ser.name: ser})

print(df)

   latin_letters
0              a
1              b
2              c
3              e
4              d
5              f
6              g
7              h
8              i
9              j
10             k
11             l
12             m
13             n
14             o
15             p
16             q
17             r
18             s
19             t
20             u
21             v
22             w
23             x
24             y
25             z


## Упражнение № 5
Из `ser1` удалите элементы, присутствующие в `ser2`.

In [7]:
import pandas as pd

ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

indices_to_remove = ser1[ser1.isin(ser2)].index
ser1_filtered = ser1.drop(indices_to_remove)

print(ser1_filtered)

0    1
1    2
2    3
dtype: int64


## Упражнение № 6
Получить все элементы `ser1` и `ser2`, которые не являются общими для обоих рядов.


In [8]:
import pandas as pd

ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

ser1_not_in_ser2 = ser1[~ser1.isin(ser2)]
ser2_not_in_ser1 = ser2[~ser2.isin(ser1)]
result = pd.concat([ser1_not_in_ser2, ser2_not_in_ser1])

print(result)


0    1
1    2
2    3
2    6
3    7
4    8
dtype: int64


## Упражнение № 7
Вычислите минимальное значение, 25-й процентиль, медиану, 75-й процентиль и максимальное значение `ser`.

In [9]:
import pandas as pd
import numpy as np

ser = pd.Series(np.random.normal(10, 5, 25))

statistics = ser.describe(percentiles=[.25, .5, .75])

print("Минимальное значение:", statistics['min'])
print("25-й процентиль:", statistics['25%'])
print("Медиана (50-й процентиль):", statistics['50%'])
print("75-й процентиль:", statistics['75%'])
print("Максимальное значение:", statistics['max'])

Минимальное значение: 4.140272639153048
25-й процентиль: 9.215013033551688
Медиана (50-й процентиль): 10.721691218199643
75-й процентиль: 12.986227753406158
Максимальное значение: 20.035046369590603


## Упражнение № 8
Вычислите частоту встречаемости каждого уникального значения `ser`.

In [10]:
import pandas as pd
import numpy as np

ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))

value_counts = ser.value_counts()

print("Частота встречаемости уникальных значений:")
print(value_counts)


Частота встречаемости уникальных значений:
a    7
f    5
h    3
g    3
e    3
c    3
d    3
b    3
Name: count, dtype: int64


## Упражнение № 9
Из `ser` оставить 2 наиболее часто встречающихся элемента без изменений, а все остальные заменить на `Прочее`.

In [11]:
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))
print(ser)

value_counts = ser.value_counts()
top_two_elements = value_counts.index[:2]
ser[~ser.isin(top_two_elements)] = 'Прочее'

print(ser)

0     2
1     1
2     2
3     2
4     1
5     3
6     3
7     4
8     1
9     4
10    1
11    4
dtype: int32
0          2
1          1
2          2
3          2
4          1
5     Прочее
6     Прочее
7     Прочее
8          1
9     Прочее
10         1
11    Прочее
dtype: object


C:\Temp\ipykernel_6272\3080988544.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Прочее' has dtype incompatible with int32, please explicitly cast to a compatible dtype first.
  ser[~ser.isin(top_two_elements)] = 'Прочее'


## Упражнение № 10
Разбейте ряд `ser` на 10 равных децилей и замените значения на название дециля.

In [12]:
import pandas as pd
import numpy as np

ser = pd.Series(np.random.random(20))
deciles = pd.qcut(ser, q=10, labels=[f'{i}th' for i in range(1, 11)])

print(deciles)

0      7th
1      5th
2      8th
3      8th
4      7th
5      6th
6      2th
7      1th
8      3th
9      9th
10    10th
11     9th
12     4th
13     5th
14     3th
15     4th
16     6th
17     1th
18    10th
19     2th
dtype: category
Categories (10, object): ['1th' < '2th' < '3th' < '4th' ... '7th' < '8th' < '9th' < '10th']


## Упражнение № 11
Переформируйте ряд `ser` в датафрейм с 7 строками и 5 столбцами

In [13]:
import pandas as pd
import numpy as np

ser = pd.Series(np.random.randint(1, 10, 35))
df = pd.DataFrame(ser.values.reshape(7, 5))

print(df)


   0  1  2  3  4
0  4  9  1  9  4
1  5  5  1  1  1
2  7  1  7  8  7
3  5  7  4  6  3
4  8  4  5  7  6
5  9  9  1  4  7
6  7  3  2  9  1


## Упражнение № 12
Найти позиции чисел, кратных 3, из ряда `ser`.

In [14]:
import pandas as pd
import numpy as np

ser = pd.Series(np.random.randint(1, 10, 7))
print(ser)
positions = ser.index[ser % 3 == 0]

print("Позиции чисел, кратных 3:", positions)


0    6
1    5
2    3
3    6
4    7
5    5
6    9
dtype: int32
Позиции чисел, кратных 3: Index([0, 2, 3, 6], dtype='int64')


## Упражнение № 13
Из `ser` извлечь элементы, находящиеся на позициях в списке `pos`.

In [15]:
import pandas as pd

ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))

pos = [0, 4, 8, 14, 20]
result = ser[pos]

print(result)


0     a
4     e
8     i
14    o
20    u
dtype: object


## Упражнение № 14
Объедините `ser1` и `ser2` по вертикали и горизонтали (чтобы сформировать датафрейм).

In [16]:
import pandas as pd

ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))

vertical_concatenation = pd.concat([ser1, ser2], axis=0)
horizontal_concatenation = pd.concat([ser1, ser2], axis=1)

print("Объединение по вертикали:")
print(vertical_concatenation)

print("\nОбъединение по горизонтали:")
print(horizontal_concatenation)


Объединение по вертикали:
0    0
1    1
2    2
3    3
4    4
0    a
1    b
2    c
3    d
4    e
dtype: object

Объединение по горизонтали:
   0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e


## Упражнение № 15
Получите позиции элементов `ser2` в `ser1` в виде списка.

In [17]:
import pandas as pd

ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])

positions = [ser1[ser1 == val].index[0] for val in ser2]
print("Позиции элементов ser2 в ser1:", positions)


Позиции элементов ser2 в ser1: [5, 4, 0, 8]


## Упражнение № 16
Вычислить среднеквадратическую ошибку рядов `truth` и `pred`.

In [18]:
import pandas as pd
import numpy as np
from sklearn.metrics import mean_squared_error

truth = pd.Series(range(10))
pred = pd.Series(range(10)) + np.random.random(10)
print(truth)
print(pred)
mse = mean_squared_error(truth, pred)

print("Среднеквадратическая ошибка (MSE):", mse)


KeyboardInterrupt: 

## Упражнение № 17
В каждом слове `ser` поставьте первый символ каждого слова в верхний регистр.

In [ ]:
import pandas as pd

ser = pd.Series(['how', 'to', 'kick', 'ass?'])
result = ser.str.title()
print(result)

0     How
1      To
2    Kick
3    Ass?
dtype: object


## Упражнение № 18
В каждом слове `ser` посчитайте число символов.

In [ ]:
import pandas as pd

ser = pd.Series(['how', 'to', 'kick', 'ass?'])
character_count = ser.str.len()
print(character_count)

0    3
1    2
2    4
3    4
dtype: int64


## Упражнение № 19

Вычислите разность разностей между последовательно идущими числами в `ser`.

In [ ]:
import pandas as pd

ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])
result = ser.diff().diff()
print(result)


0      NaN
1      NaN
2   1.0000
3   1.0000
4   1.0000
5   1.0000
6   0.0000
7   2.0000
dtype: float64


## Упражнение № 20

Преобразуйте строковое представление дат в `datetime64`.

In [ ]:
import pandas as pd

ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

converted_dates = pd.to_datetime(ser, errors='coerce', infer_datetime_format=True)
print(converted_dates)


0   2010-01-01
1          NaT
2          NaT
3          NaT
4          NaT
5          NaT
dtype: datetime64[ns]


C:\Temp\ipykernel_5576\981038107.py:5: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  converted_dates = pd.to_datetime(ser, errors='coerce', infer_datetime_format=True)


## Упражнение № 21

Получите из `ser` день месяца, номер недели, день года и день недели.

In [ ]:
import pandas as pd

# Создаем серию
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

# Преобразуем строки в datetime64
dates = pd.to_datetime(ser, errors='coerce')

# Извлекаем нужные компоненты
day_of_month = dates.dt.day
week_number = dates.dt.isocalendar().week
day_of_year = dates.dt.dayofyear
day_of_week = dates.dt.day_name()

# Выводим результаты
print("Date: ", day_of_month.tolist())
print("Week number: ", week_number.tolist())
print("Day num of year: ", day_of_year.tolist())
print("Day of week: ", day_of_week.tolist())


Date:  [1.0, nan, nan, nan, nan, nan]
Week number:  [53, <NA>, <NA>, <NA>, <NA>, <NA>]
Day num of year:  [1.0, nan, nan, nan, nan, nan]
Day of week:  ['Friday', nan, nan, nan, nan, nan]


## Упражнение № 22

Замените элементы `ser` на даты, начинающиеся с 4-го числа соответствующего месяца.

In [ ]:
import pandas as pd

# Создаем серию
ser = pd.Series(['Jan 2010', 'Feb 2011', 'Mar 2012'])

# Преобразуем строки в datetime64, начиная с 4-го числа месяца
converted_dates = pd.to_datetime(ser, format='%b %Y', errors='coerce') + pd.offsets.MonthBegin(0) + pd.DateOffset(days=3)

# Выводим результаты
print(converted_dates)


0   2010-01-04
1   2011-02-04
2   2012-03-04
dtype: datetime64[ns]


## Упражнение № 23

Из `ser` извлеките слова, содержащие не менее 2 гласных букв.

In [ ]:
import pandas as pd

ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Money'])
def count_vowels(word):
    vowels = set("AEIOUaeiou")
    return sum(1 for char in word if char in vowels)

result = ser[ser.apply(count_vowels) >= 2]
print(result)


0     Apple
1    Orange
4     Money
dtype: object


## Упражнение № 24

Извлеките корректные адреса электронной почты из ряда `emails`.

In [ ]:
import pandas as pd

# Создаем серию
emails = pd.Series(['buying books at amazom.com', 'rameses@egypt.com', 'matt@t.co', 'narendra@modi.com'])
pattern ='[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}'

# Извлекаем корректные адреса электронной почты
correct_emails = emails[emails.str.contains(pattern, na=False)]

# Выводим результаты
print(correct_emails)


1    rameses@egypt.com
2            matt@t.co
3    narendra@modi.com
dtype: object


## Упражнение № 25

Вычислить среднее значение веса в `weights` для каждого фрукта из `fruit`.

In [ ]:
import pandas as pd
import numpy as np

fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))
print(fruit.tolist())
print(weights.tolist())

df = pd.DataFrame({'fruit': fruit, 'weight': weights})
average_weight = df.groupby('fruit')['weight'].mean()
print(average_weight)


['carrot', 'carrot', 'banana', 'carrot', 'apple', 'apple', 'apple', 'banana', 'banana', 'apple']
[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
fruit
apple    7.0000
banana   6.6667
carrot   2.3333
Name: weight, dtype: float64


## Упражнение № 26

Вычислить [евклидово расстояние](https://en.wikipedia.org/wiki/Euclidean_distance) между векторами $p$ и $q$, не используя встроенную формулу.

In [ ]:
import pandas as pd

# Создаем векторы p и q
p = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
q = pd.Series([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])

# Вычисляем евклидово расстояние
euclidean_distance = ((p - q) ** 2).sum() ** 0.5

# Выводим результат
print(round(euclidean_distance, 3))


18.166


## Упражнение № 27

Получите позиции пиков (значений, окруженных с двух сторон меньшими значениями) в `ser`.

In [ ]:
import pandas as pd
from scipy.signal import find_peaks

# Создаем серию
ser = pd.Series([2, 10, 3, 4, 9, 10, 2, 7, 3])

# Находим позиции пиков
peaks, _ = find_peaks(ser)

# Выводим результаты
print(peaks)


[1 5 7]


## Упражнение № 28

Замените пробелы в `my_str` на наименее часто встречающийся символ.

In [ ]:
from collections import Counter

# Исходная строка
my_str = 'dbc deb abed gade'

# Подсчитываем частоту каждого символа, игнорируя пробелы
counter = Counter(char for char in my_str if char != ' ')

# Находим наименее часто встречающийся символ
least_frequent_char = min(counter, key=counter.get)

# Заменяем пробелы на наименее часто встречающийся символ
result_str = ''.join(char if char != ' ' else least_frequent_char for char in my_str)

# Выводим результат
print(result_str)


dbccdebcabedcgade


## Упражнение № 29

Создайте временной ряд, начинающийся с `2000-01-01`, содержащий 10 субботних дней после этого и имеющий в качестве значений случайные числа

In [ ]:
import pandas as pd
import numpy as np

# Устанавливаем начальную дату
start_date = pd.to_datetime('2000-01-01')

# Создаем временной ряд с 10 субботними днями
date_index = pd.date_range(start_date, periods=10, freq='W-SAT')

# Генерируем случайные значения
random_values = np.random.randint(1, 10, size=10)

# Создаем временной ряд
time_series = pd.Series(random_values, index=date_index)

# Выводим результат
print(time_series)


2000-01-01    7
2000-01-08    4
2000-01-15    2
2000-01-22    5
2000-01-29    7
2000-02-05    9
2000-02-12    6
2000-02-19    4
2000-02-26    5
2000-03-04    1
Freq: W-SAT, dtype: int32


## Упражнение № 30

В `ser` отсутствуют некоторые даты и значения. Сделайте так, чтобы все отсутствующие даты появились и заполнились значением из предыдущей даты.

In [ ]:
import pandas as pd
import numpy as np

# Создаем серию
ser = pd.Series([1, 10, 3, np.nan], index=pd.to_datetime(['2000-01-01', '2000-01-03', '2000-01-06', '2000-01-08']))

# Заполняем отсутствующие даты значениями из предыдущей даты
filled_ser = ser.asfreq('D', method='pad')

# Выводим результат
print(filled_ser)


2000-01-01    1.0000
2000-01-02    1.0000
2000-01-03   10.0000
2000-01-04   10.0000
2000-01-05   10.0000
2000-01-06    3.0000
2000-01-07    3.0000
2000-01-08       NaN
Freq: D, dtype: float64


## Упражнение № 31

Вычислите автокорреляции для первых 10 лагов `ser`. Определите, какой из лагов имеет наибольшую корреляцию.

In [ ]:
import pandas as pd
import numpy as np

# Создаем серию
ser = pd.Series(np.arange(20) + np.random.normal(1, 10, 20))

# Вычисляем автокорреляции для первых 10 лагов
autocorrelations = [ser.autocorr(i) for i in range(1, 11)]

# Выводим результаты
print(autocorrelations)
print("Lag having highest correlation:", np.argmax(np.abs(autocorrelations)) + 1)


[-0.2249699300317032, 0.013154629956023029, 0.7233830050416213, -0.14658728021737533, 0.09174835363329727, 0.5629621418723846, -0.33238209330279794, 0.3504040789428592, 0.29930491543971643, -0.7199444389858849]
Lag having highest correlation: 3


## Упражнение № 32

Импортируйте каждую 50-ю строку набора данных [BostonHousing dataset](https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv) в виде датафрейма.

In [ ]:
import pandas as pd

# URL набора данных
url = 'https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv'

# Загрузка данных
boston_data = pd.read_csv(url)

# Импорт каждой 50-й строки в виде датафрейма
every_50th_row = boston_data.iloc[::50, :]

# Вывод результата
print(every_50th_row)


       crim      zn   indus  chas    nox  ...  tax  ptratio        b   lstat  \
0    0.0063 18.0000  2.3100     0 0.5380  ...  296  15.3000 396.9000  4.9800   
50   0.0887 21.0000  5.6400     0 0.4390  ...  243  16.8000 395.5600 13.4500   
100  0.1487  0.0000  8.5600     0 0.5200  ...  384  20.9000 394.7600  9.4200   
150  1.6566  0.0000 19.5800     0 0.8710  ...  403  14.7000 372.8000 14.1000   
200  0.0178 95.0000  1.4700     0 0.4030  ...  402  17.0000 384.3000  4.4500   
250  0.1403 22.0000  5.8600     0 0.4310  ...  330  19.1000 396.2800  5.9000   
300  0.0442 70.0000  2.2400     0 0.4000  ...  358  14.8000 390.8600  6.0700   
350  0.0621 40.0000  1.2500     0 0.4290  ...  335  19.7000 396.9000  5.9800   
400 25.0461  0.0000 18.1000     0 0.6930  ...  666  20.2000 396.9000 26.7700   
450  6.7177  0.0000 18.1000     0 0.7130  ...  666  20.2000   0.3200 17.4400   
500  0.2244  0.0000  9.6900     0 0.5850  ...  391  19.2000 396.9000 14.3300   

       medv  
0   24.0000  
50  19.7000

## Упражнение № 33

Импортируйте набор данных [boston housing dataset](https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv), но при импорте измените столбец `'medv'` (*median house value*) так, чтобы значения < 25 стали `Low`, а > 25 - `High`.

In [ ]:
import pandas as pd

# URL набора данных
url = 'https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv'

# Загрузка данных
boston_data = pd.read_csv(url)

# Изменение значения столбца 'medv'
boston_data['medv'] = boston_data['medv'].apply(lambda x: 'Low' if x < 25 else 'High')

# Вывод результата
print(boston_data.head())


    crim      zn  indus  chas    nox  ...  tax  ptratio        b  lstat  medv
0 0.0063 18.0000 2.3100     0 0.5380  ...  296  15.3000 396.9000 4.9800   Low
1 0.0273  0.0000 7.0700     0 0.4690  ...  242  17.8000 396.9000 9.1400   Low
2 0.0273  0.0000 7.0700     0 0.4690  ...  242  17.8000 392.8300 4.0300  High
3 0.0324  0.0000 2.1800     0 0.4580  ...  222  18.7000 394.6300 2.9400  High
4 0.0691  0.0000 2.1800     0 0.4580  ...  222  18.7000 396.9000 5.3300  High

[5 rows x 14 columns]


## Упражнение № 34

Создайте датафрейм со строками в виде шагов (интервалов) заданного ряда

In [ ]:
import pandas as pd
import numpy as np

# Задаем ряд
L = pd.Series(range(15))

# Создаем датафрейм со строками в виде шагов
step_size = 4
df = pd.concat([L.shift(-i) for i in range(step_size)], axis=1).dropna().astype(int)

# Выводим результат
print(df.values)


[[ 0  1  2  3]
 [ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


## Упражнение № 35

Импортируйте столбцы 'crim' и 'medv' из набора данных [BostonHousing dataset](https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv) в виде датафрейма.

In [ ]:
import pandas as pd

# URL набора данных
url = 'https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv'

# Загрузка данных
boston_data = pd.read_csv(url, usecols=['crim', 'medv'])

# Вывод результата
print(boston_data.head())


    crim    medv
0 0.0063 24.0000
1 0.0273 21.6000
2 0.0273 34.7000
3 0.0324 33.4000
4 0.0691 36.2000


## Упражнение № 36

Получите количество строк, столбцов, тип данных и суммарную статистику каждого столбца набора данных [Cars93](https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv). Также получите эквивалент датафрейма в виде numpy-массива и списка.

In [ ]:
import pandas as pd
import numpy as np

# URL набора данных
url = 'https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv'

# Загрузка данных
cars_data = pd.read_csv(url)

# Информация о датафрейме
info_df = cars_data.info()

# Эквивалент в виде numpy-массива
numpy_array = cars_data.to_numpy()

# Эквивалент в виде списка
list_of_lists = cars_data.values.tolist()

# Вывод результатов
print("Информация о датафрейме:")
print(info_df)
print("\nЭквивалент в виде numpy-массива:")
print(numpy_array)
print("\nЭквивалент в виде списка:")
print(list_of_lists)


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 27 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Manufacturer        89 non-null     object 
 1   Model               92 non-null     object 
 2   Type                90 non-null     object 
 3   Min.Price           86 non-null     float64
 4   Price               91 non-null     float64
 5   Max.Price           88 non-null     float64
 6   MPG.city            84 non-null     float64
 7   MPG.highway         91 non-null     float64
 8   AirBags             55 non-null     object 
 9   DriveTrain          86 non-null     object 
 10  Cylinders           88 non-null     object 
 11  EngineSize          91 non-null     float64
 12  Horsepower          86 non-null     float64
 13  RPM                 90 non-null     float64
 14  Rev.per.mile        87 non-null     float64
 15  Man.trans.avail     88 non-null     object 
 16  Fuel.tank.

## Упражнение № 37

Извлеките номер строки и столбца конкретной ячейки по заданному критерию.

In [ ]:
import pandas as pd

# Загрузка данных
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Находим индекс максимального значения в столбце 'Price'
max_price_index = df['Price'].idxmax()

# Получаем значение максимальной цены
max_price = df.loc[max_price_index, 'Price']

# Получаем номер строки и столбца ячейки с максимальным значением 'Price'
row, col = df.index.get_loc(max_price_index), df.columns.get_loc('Price')

# Вывод результатов
print("Производитель, модель и тип с наибольшей ценой:")
print(df.loc[max_price_index, ['Manufacturer', 'Model', 'Type']])
print("\nМаксимальная цена:", max_price)
print("\nНомер строки и столбца ячейки с максимальной ценой:")
print("Номер строки:", row)
print("Номер столбца ('Price'):", col)


Производитель, модель и тип с наибольшей ценой:
Manufacturer    Mercedes-Benz
Model                    300E
Type                  Midsize
Name: 58, dtype: object

Максимальная цена: 61.9

Номер строки и столбца ячейки с максимальной ценой:
Номер строки: 58
Номер столбца ('Price'): 4


## Упражнение № 38

Переименуйте в `df` столбец `Type` в `CarType` и замените `.` в именах столбцов на `_`.

In [ ]:
import pandas as pd

# Загрузка данных
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Переименование столбца 'Type' в 'CarType' и замена точек в именах столбцов
df.rename(columns={'Type': 'CarType'}, inplace=True)
df.columns = df.columns.str.replace('.', '_')

# Вывод результатов
print(df.columns)


Index(['Manufacturer', 'Model', 'CarType', 'Min_Price', 'Price', 'Max_Price',
       'MPG_city', 'MPG_highway', 'AirBags', 'DriveTrain', 'Cylinders',
       'EngineSize', 'Horsepower', 'RPM', 'Rev_per_mile', 'Man_trans_avail',
       'Fuel_tank_capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
       'Turn_circle', 'Rear_seat_room', 'Luggage_room', 'Weight', 'Origin',
       'Make'],
      dtype='object')


## Упражнение № 39

Проверьте, нет ли в `df` отсутствующих значений.

In [ ]:
import pandas as pd

# Загрузка данных
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Проверка наличия отсутствующих значений
missing_values = df.isna().any().any()

# Вывод результата
print("Наличие отсутствующих значений:", missing_values)


Наличие отсутствующих значений: True


## Упражнение № 40

Подсчитайте количество пропущенных значений в каждом столбце `df`. Какой столбец имеет наибольшее число пропущенных значений?

In [ ]:
import pandas as pd

# Загрузка данных
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Подсчет количества пропущенных значений в каждом столбце
missing_values_count = df.isna().sum()

# Определение столбца с наибольшим числом пропущенных значений
max_missing_column = missing_values_count.idxmax()
max_missing_count = missing_values_count.max()

# Вывод результатов
print("Количество пропущенных значений в каждом столбце:")
print(missing_values_count)
print("\nСтолбец с наибольшим числом пропущенных значений:")
print(f"Столбец: {max_missing_column}, Количество пропущенных: {max_missing_count}")


Количество пропущенных значений в каждом столбце:
Manufacturer           4
Model                  1
Type                   3
Min.Price              7
Price                  2
Max.Price              5
MPG.city               9
MPG.highway            2
AirBags               38
DriveTrain             7
Cylinders              5
EngineSize             2
Horsepower             7
RPM                    3
Rev.per.mile           6
Man.trans.avail        5
Fuel.tank.capacity     8
Passengers             2
Length                 4
Wheelbase              1
Width                  6
Turn.circle            5
Rear.seat.room         4
Luggage.room          19
Weight                 7
Origin                 5
Make                   3
dtype: int64

Столбец с наибольшим числом пропущенных значений:
Столбец: AirBags, Количество пропущенных: 38


## Упражнение № 41

Замените отсутствующие значения в столбцах `Min.Price` и `Max.Price` на соответствующие им средние значения.

In [ ]:
import pandas as pd

# Загрузка данных
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Замена отсутствующих значений в столбце 'Min.Price' на среднее значение
df['Min.Price'].fillna(df['Min.Price'].mean(), inplace=True)

# Замена отсутствующих значений в столбце 'Max.Price' на среднее значение
df['Max.Price'].fillna(df['Max.Price'].mean(), inplace=True)

# Вывод результата
print("Данные после замены отсутствующих значений:")
print(df[['Min.Price', 'Max.Price']])


Данные после замены отсутствующих значений:
    Min.Price  Max.Price
0     12.9000    18.8000
1     29.2000    38.7000
2     25.9000    32.3000
3     17.1186    44.6000
4     17.1186    21.4591
..        ...        ...
88    16.6000    22.7000
89    17.6000    22.4000
90    22.9000    23.7000
91    21.8000    23.5000
92    24.8000    28.5000

[93 rows x 2 columns]


## Упражнение № 42

В `df` с помощью метода `apply` замените недостающие значения в `Min.Price` на среднее значение столбца, а в `Max.Price` — на медиану столбца.

In [ ]:
import pandas as pd

# Загрузка данных
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Определение функции для замены отсутствующих значений на среднее значение
def fillna_mean(column):
    return column.fillna(column.mean())

# Определение функции для замены отсутствующих значений на медиану
def fillna_median(column):
    return column.fillna(column.median())

# Замена отсутствующих значений в столбце 'Min.Price' на среднее значение
df['Min.Price'] = df[['Min.Price']].apply(fillna_mean, axis=0)

# Замена отсутствующих значений в столбце 'Max.Price' на медиану
df['Max.Price'] = df[['Max.Price']].apply(fillna_median, axis=0)

# Вывод результата
print("Данные после замены отсутствующих значений:")
print(df[['Min.Price', 'Max.Price']])


Данные после замены отсутствующих значений:
    Min.Price  Max.Price
0     12.9000    18.8000
1     29.2000    38.7000
2     25.9000    32.3000
3     17.1186    44.6000
4     17.1186    19.1500
..        ...        ...
88    16.6000    22.7000
89    17.6000    22.4000
90    22.9000    23.7000
91    21.8000    23.5000
92    24.8000    28.5000

[93 rows x 2 columns]


## Упражнение № 43

Получите первый столбец (`a`) в `df` в виде датафрейма (а не в виде ряда).

In [ ]:
import pandas as pd
import numpy as np

# Создание исходного датафрейма
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))

# Получение первого столбца в виде датафрейма
first_column_df = df[['a']]

# Вывод результата
print("Первый столбец в виде датафрейма:")
print(first_column_df)


Первый столбец в виде датафрейма:
    a
0   0
1   5
2  10
3  15


## Упражнение № 44

1. В `df` поменяйте местами столбцы `'a'` и `'c'`.
2. Создайте обобщенную функцию для обмена данными между двумя столбцами без фиксированного задания имен столбцов.
3. Отсортируйте столбцы в обратном алфавитном порядке, т.е. от столбца `'e'` до столбца `'a'`.

In [ ]:
import pandas as pd
import numpy as np

# Создание исходного датафрейма
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))
print("Изначальный DataFrame: ")
print(df)
# 1. Поменять местами столбцы 'a' и 'c'
df[['a', 'c']] = df[['c', 'a']]

# Вывод результата после первого шага
print("После обмена местами столбцов 'a' и 'c':")
print(df)

# 2. Создать обобщенную функцию для обмена данными между двумя столбцами
def swap_columns(df, col1, col2):
    df[col1], df[col2] = df[col2].copy(), df[col1].copy()

# Пример использования:
swap_columns(df, 'a', 'c')
print("\nПосле использования обобщенной функции для обмена столбцов 'a' и 'c':")
print(df)

# 3. Отсортировать столбцы в обратном алфавитном порядке
df = df[sorted(df.columns, reverse=True)]
print("\nПосле сортировки столбцов в обратном алфавитном порядке:")
print(df)


Изначальный DataFrame: 
    a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
После обмена местами столбцов 'a' и 'c':
    a   b   c   d   e
0   2   1   0   3   4
1   7   6   5   8   9
2  12  11  10  13  14
3  17  16  15  18  19

После использования обобщенной функции для обмена столбцов 'a' и 'c':
    a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

После сортировки столбцов в обратном алфавитном порядке:
    e   d   c   b   a
0   4   3   2   1   0
1   9   8   7   6   5
2  14  13  12  11  10
3  19  18  17  16  15


## Упражнение № 45

Измените настройки отображения `pandas` при выводе на печать датафрейма `df`, чтобы он показывал максимум 10 строк и 10 столбцов.

In [ ]:
import pandas as pd

# Загрузка данных
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Изменение настроек отображения
pd.set_option('display.max_rows', 10)
pd.set_option('display.max_columns', 10)

# Вывод датафрейма
print(df)


   Manufacturer    Model     Type  Min.Price   Price  ...  Rear.seat.room  \
0         Acura  Integra    Small    12.9000 15.9000  ...         26.5000   
1           NaN   Legend  Midsize    29.2000 33.9000  ...         30.0000   
2          Audi       90  Compact    25.9000 29.1000  ...         28.0000   
3          Audi      100  Midsize        NaN 37.7000  ...         31.0000   
4           BMW     535i  Midsize        NaN 30.0000  ...         27.0000   
..          ...      ...      ...        ...     ...  ...             ...   
88   Volkswagen  Eurovan      Van    16.6000 19.7000  ...         34.0000   
89   Volkswagen   Passat  Compact    17.6000 20.0000  ...         31.5000   
90   Volkswagen  Corrado   Sporty    22.9000 23.3000  ...         26.0000   
91        Volvo      240  Compact    21.8000 22.7000  ...         29.5000   
92          NaN      850  Midsize    24.8000 26.7000  ...         30.0000   

    Luggage.room    Weight   Origin                Make  
0            NaN 

## Упражнение № 46

Исключите вывод научной нотации типа 'e-03' в `df` и выведите до 4 чисел после запятой.

In [ ]:
import pandas as pd
import numpy as np

# Создание датафрейма
df = pd.DataFrame(np.random.random(4)**10, columns=['random'])

# Исключение научной нотации и вывод чисел с 4 знаками после запятой
pd.set_option('display.float_format', '{:.4f}'.format)

# Вывод датафрейма
print(df)


   random
0  0.0846
1  0.6055
2  0.2987
3  0.0008


## Упражнение № 47

Отформатируйте значения в столбце `'random'` из `df` в виде процентов.

In [ ]:
import pandas as pd
import numpy as np

# Создание датафрейма
df = pd.DataFrame(np.random.random(4), columns=['random'])
print(df)

# Форматирование значения в проценты
df['random'] = df['random'].apply(lambda x: '{:.2%}'.format(x))

# Вывод датафрейма
print(df)


   random
0  0.1081
1  0.2668
2  0.4678
3  0.1130
   random
0  10.81%
1  26.68%
2  46.78%
3  11.30%


## Упражнение № 48

Из `df` отфильтруйте значения `Manufacturer`, `Model` и `Type` для каждой 20-й строки, начиная с 1-й (строка 0).

In [ ]:
import pandas as pd

# Загрузка данных
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Отфильтровывание значений
filtered_values = df.loc[1::20, ['Manufacturer', 'Model', 'Type']]

# Вывод результатов
print(filtered_values)


   Manufacturer     Model     Type
1           NaN    Legend  Midsize
21     Chrysler  Imperial    Large
41        Honda     Civic    Small
61   Mitsubishi    Mirage    Small
81       Subaru    Legacy  Compact


## Упражнение № 49

В `df` замените `NaN` на `missing` в столбцах `Manufacturer`, `Model` и `Type` , создайте индекс как комбинацию этих трех столбцов и проверьте, является ли этот индекс первичным ключом.

In [ ]:
import pandas as pd

# Загрузка данных
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv', usecols=[0, 1, 2, 3, 5])

# Замена NaN на 'missing' в указанных столбцах
df[['Manufacturer', 'Model', 'Type']] = df[['Manufacturer', 'Model', 'Type']].fillna('missing')

# Создание индекса как комбинации столбцов 'Manufacturer', 'Model' и 'Type'
df.set_index(['Manufacturer', 'Model', 'Type'], inplace=True)

# Проверка, является ли индекс первичным ключом
is_primary_key = df.index.is_unique

# Вывод результатов
print(df)
print("\nIs the index a primary key?", is_primary_key)


                              Min.Price  Max.Price
Manufacturer Model   Type                         
Acura        Integra Small      12.9000    18.8000
missing      Legend  Midsize    29.2000    38.7000
Audi         90      Compact    25.9000    32.3000
             100     Midsize        NaN    44.6000
BMW          535i    Midsize        NaN        NaN
...                                 ...        ...
Volkswagen   Eurovan Van        16.6000    22.7000
             Passat  Compact    17.6000    22.4000
             Corrado Sporty     22.9000    23.7000
Volvo        240     Compact    21.8000    23.5000
missing      850     Midsize    24.8000    28.5000

[93 rows x 2 columns]

Is the index a primary key? True


## Упражнение № 50

Найти положение строки с 5-м наибольшим значением столбца `'a'` в `df`.

In [ ]:
import pandas as pd
import numpy as np

# Пример DataFrame
df = pd.DataFrame(np.random.randint(1, 30, 30).reshape(10, -1), columns=list('abc'))
print(df)
# Найти положение строки с 5-м наибольшим значением в столбце 'a'
index_of_5th_largest = df['a'].nlargest(5).index[-1]

# Вывести результат
print("Индекс строки с 5-м наибольшим значением в столбце 'a':", index_of_5th_largest)


    a   b   c
0  11  24  20
1   7  19  17
2  20  18  19
3   1  12  13
4  12  11  13
5  17  20  23
6   3  15   8
7   7  23  17
8   4  16   8
9  21  25  11
Индекс строки с 5-м наибольшим значением в столбце 'a': 0


## Упражнение № 51

В `ser` найдите положение 2-го наибольшего значения, превышающего среднее.

In [ ]:
import pandas as pd
import numpy as np
# pd.set_option('display.max_rows', 30)
# Пример Series
ser = pd.Series(np.random.randint(1, 100, 15))
print(ser)
# Найти положение 2-го наибольшего значения, превышающего среднее
mean_value = ser.mean()
filtered_values = ser[ser > mean_value].nlargest(2)
position_of_2nd_largest_above_mean = filtered_values.index[-1]

# Вывести результат
print("Положение 2-го наибольшего значения, превышающего среднее:", position_of_2nd_largest_above_mean)


0     84
1     43
2     71
3     40
4     35
      ..
10    77
11     1
12    49
13    95
14    44
Length: 15, dtype: int32
Положение 2-го наибольшего значения, превышающего среднее: 7


## Упражнение № 52

Получите две последние строки `df`, сумма строк которых больше 100.

In [ ]:
import pandas as pd
import numpy as np

# Пример DataFrame
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
print(df)
# Выбрать две последние строки сумма которых больше 100
filtered_rows = df[df.sum(axis=1) > 100].tail(2)

# Вывести результат
print(filtered_rows)


     0   1   2   3
0   16  31  34  18
1   16  19  30  33
2   36  36  34  39
3   37  11  31  15
4   24  28  25  15
..  ..  ..  ..  ..
10  15  28  28  31
11  28  37  14  36
12  15  39  13  14
13  21  23  16  16
14  10  16  39  25

[15 rows x 4 columns]
     0   1   2   3
10  15  28  28  31
11  28  37  14  36


## Упражнение № 53

Замените все значения `ser`, находящиеся ниже 5%-ного и выше 95%-ного перцентиля, на соответствующие значения 5-го и 95-го перцентиля.

In [ ]:
import pandas as pd
import numpy as np

# Пример Series
ser = pd.Series(np.logspace(-2, 2, 30))

# Находим 5-й и 95-й перцентили
percentile_5 = ser.quantile(0.05)
percentile_95 = ser.quantile(0.95)

# Заменяем значения вне диапазона на соответствующие перцентили
ser = ser.apply(lambda x: x if percentile_5 <= x <= percentile_95 else (percentile_5 if x < percentile_5 else percentile_95))

# Вывод результата
print(ser)


0     0.0160
1     0.0160
2     0.0189
3     0.0259
4     0.0356
       ...  
25   28.0722
26   38.5662
27   52.9832
28   63.8767
29   63.8767
Length: 30, dtype: float64


## Упражнение № 54

Перестройте `df` в максимально возможный квадрат с удалением отрицательных значений. При необходимости отбросьте наименьшие значения. Порядок положительных чисел в результате должен остаться тем же, что и в исходном варианте.

In [ ]:
import pandas as pd
import numpy as np

# Пример DataFrame
df = pd.DataFrame(np.random.randint(-20, 50, 100).reshape(10, -1))
print(df)
# Удаление отрицательных значений
df[df < 0] = np.nan

# Удаление строки с наименьшими значениями
df = df.drop(df.sum(axis=1).idxmin())

# Перестройка в квадрат
df = df.apply(lambda x: x.sort_values(ascending=False).values)
df = df.apply(lambda x: pd.Series(x.dropna().values))

# Вывод результата
print(df)


    0   1   2   3   4   5   6   7   8   9
0 -16  11  27   0   7  14 -12 -18  25   6
1  17  23  45  33  43  30  -8  29 -12  14
2  26  47  24  -7  47  19   9 -10  41   9
3  14 -16  -8   3  20  29 -13  -8   4  32
4  40  35  32 -18  34  16  25  18  13  45
5  -6   6  20  43  49  25  22  46   2  37
6   8  40   7   6  48  37  49   4  14  26
7  -2  36  25  25   2  -3  44  40  47  -1
8  19  24  34  11  30  44  19  34 -13  43
9  26  48  10  45  -3  13  45  48  11   1
        0       1       2       3       4       5       6       7       8  \
0 40.0000 48.0000 45.0000 45.0000 49.0000 44.0000 49.0000 48.0000 47.0000   
1 26.0000 47.0000 34.0000 43.0000 48.0000 37.0000 45.0000 46.0000 41.0000   
2 26.0000 40.0000 32.0000 33.0000 47.0000 30.0000 44.0000 40.0000 14.0000   
3 19.0000 36.0000 25.0000 25.0000 43.0000 29.0000 25.0000 34.0000 13.0000   
4 17.0000 35.0000 24.0000 11.0000 34.0000 25.0000 22.0000 29.0000 11.0000   
5 14.0000 24.0000 20.0000  6.0000 30.0000 19.0000 19.0000 18.0000  4.0000   

## Упражнение № 56

Переверните строки датафрейма `df` (первая строка становится последней).

In [ ]:
import pandas as pd
import numpy as np

# Пример DataFrame
df = pd.DataFrame(np.arange(25).reshape(5, -1))
print(df)
# Переворот строк
df_flipped = df.iloc[::-1]

# Вывод результата
print(df_flipped)


    0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24
    0   1   2   3   4
4  20  21  22  23  24
3  15  16  17  18  19
2  10  11  12  13  14
1   5   6   7   8   9
0   0   1   2   3   4


## Упражнение № 57

Получите бинарный код для столбца `'a'` в датафрейме `df` и добавьте его в виде столбцов.

In [ ]:
import pandas as pd
import numpy as np

# Пример DataFrame
df = pd.DataFrame(np.arange(25).reshape(5, -1), columns=list('abcde'))
# Получение бинарного кода для столбца 'a'
binary_code = pd.get_dummies(df['a'], prefix='a')

# Добавление бинарного кода в виде столбцов в DataFrame
df_with_binary = pd.concat([binary_code, df], axis=1)

# Вывод результата
print(df_with_binary)


     a_0    a_5   a_10   a_15   a_20   a   b   c   d   e
0   True  False  False  False  False   0   1   2   3   4
1  False   True  False  False  False   5   6   7   8   9
2  False  False   True  False  False  10  11  12  13  14
3  False  False  False   True  False  15  16  17  18  19
4  False  False  False  False   True  20  21  22  23  24


## Упражнение № 58

Получите название столбца с наибольшим количеством строчных максимумов в `df`.

In [ ]:
import pandas as pd
import numpy as np

# Пример DataFrame
df = pd.DataFrame(np.random.randint(1, 100, 40).reshape(10, -1))
print(df)
# Функция для подсчета максимумов в каждом столбце
def count_lowercase_max(column):
    return column.apply(lambda x: sum(map(str.islower, str(x))))

# Название столбца с наибольшим количеством строчных максимумов
max_lowercase_col = df.apply(count_lowercase_max).idxmax()

# Вывод результата
print("Столбец с наибольшим количеством строчных максимумов:", max_lowercase_col)


    0   1   2   3
0   6  84  84  72
1  90  64  44  23
2  71   2  21  22
3  69  90  91  15
4  54  44   6  89
5  25  61  45  47
6  10  55  16  23
7  33  59  67  69
8  34  36  63  79
9  23  51  25  34
Столбец с наибольшим количеством строчных максимумов: 0    0
1    0
2    0
3    0
dtype: int64


## Упражнение № 59

Создать новый столбец, в каждой строке которого будет указан номер строки, ближайшей по евклидову расстоянию к данной строке.

## Упражнение № 60

Вычислите максимально возможное абсолютное значение корреляции каждого столбца с другими столбцами в `df`.

In [ ]:
import pandas as pd
import numpy as np

# Пример DataFrame
df = pd.DataFrame(np.random.randint(1, 100, 80).reshape(8, -1), columns=list('pqrstuvwxy'), index=list('abcdefgh'))
print(df)
# Функция для вычисления максимально возможной абсолютной корреляции
def max_possible_corr(column, df):
    max_corr = 0
    for other_column in df.columns:
        if column != other_column:
            corr = np.abs(df[column].corr(df[other_column]))
            max_corr = max(max_corr, corr)
    return max_corr

# Вычисление максимально возможной абсолютной корреляции для каждого столбца
max_corrs = {column: max_possible_corr(column, df) for column in df.columns}

# Вывод результата
print(max_corrs)


    p   q   r   s   t   u   v   w   x   y
a  73  76  50  28  95  66  86  29  35  42
b  42  85  37  83  46  86  75  66  43  78
c  30  91  57  60   4  34  58  13   1  42
d  31  19   5  87  13  12  32  58  39  47
e  54  11  30  67  34  19  47  24  99  85
f  97   2  25  35  50  36   7  57  50  50
g  37  30  27  28  42  55  95  24  29  36
h  88  99  53  94  31  98  22  75  34  31
{'p': 0.5203860401082717, 'q': 0.8225419174363632, 'r': 0.8225419174363632, 's': 0.5879721803306412, 't': 0.5770732086821655, 'u': 0.7296027953134212, 'v': 0.5351955372809225, 'w': 0.5879721803306414, 'x': 0.7320663604451946, 'y': 0.7320663604451947}


## Упражнение № 61

Вычислите минимум-максимум для каждой строки `df`.

In [ ]:
import pandas as pd
import numpy as np

# Пример DataFrame
df = pd.DataFrame(np.random.randint(1, 100, 80).reshape(8, -1))
print(df)
# Функция для вычисления минимум-максимума
def min_max(row):
    return (row.min(), row.max())

# Применение функции к каждой строке
min_max_values = df.apply(min_max, axis=1)

# Создание нового DataFrame с результатами
result_df = pd.DataFrame(min_max_values.tolist(), columns=['Min', 'Max'])

# Вывод результата
print(result_df)


    0   1   2   3   4   5   6   7   8   9
0  42   6  90  48  61  77  29  12  87  49
1  56  26  40  20  76  19  14  23  51  33
2  39  84  35  93  72  11  67   6  23  73
3  85  13  84   1  44  27  28  68  15  25
4  63  64  66  40  29  43   5  68  63  36
5  98  44  40   1  11  59  22  75  15  58
6  66  66  41  26  99  51   7  10  99  49
7  25  47  76  54  63  84   4  34  54  78
   Min  Max
0    6   90
1   14   76
2    6   93
3    1   85
4    5   68
5    1   98
6    7   99
7    4   84


## Упражнение № 62

Создайте новый столбец `penultimate`, который содержит второе по величине значение каждой строки `df`.

In [ ]:
import pandas as pd
import numpy as np

# Пример DataFrame
df = pd.DataFrame(np.random.randint(1, 100, 80).reshape(8, -1))

# Функция для получения второго по величине значения
def second_largest(row):
    sorted_row = sorted(row, reverse=True)
    return sorted_row[1] if len(sorted_row) > 1 else np.nan

# Применение функции к каждой строке
df['penultimate'] = df.apply(second_largest, axis=1)

# Вывод результата
print(df)


    0   1   2   3   4  ...   6   7   8   9  penultimate
0  31  15  88  60  60  ...   2  34  68  10           68
1  14  88  92  45  38  ...  18  58  82  24           91
2   4  35  29  52  95  ...  72  78  15  25           78
3  87  19  57  37   5  ...   3  36  94  78           88
4  28  36  98  60  76  ...  49  69  80  96           96
5  47  29   8  36   3  ...  72   6  73  25           72
6  91  48  21  78  86  ...  69  19  51  50           86
7  25  94   3  45  69  ...  28  52  68  51           69

[8 rows x 11 columns]


## Упражнение № 63

1. Нормализуйте все столбцы `df`, вычитая среднее значение столбца и деля его на стандартное отклонение.
2. Произведите ранжирование всех столбцов `df` таким образом, чтобы минимальное значение в каждом столбце было равно 0, а максимальное — 1.

In [ ]:
import pandas as pd
import numpy as np

# Пример DataFrame
df = pd.DataFrame(np.random.randint(1, 100, 80).reshape(8, -1))

# Нормализация: вычитание среднего и деление на стандартное отклонение
normalized_df = (df - df.mean()) / df.std()

# Вывод нормализованного DataFrame
print("Нормализованный DataFrame:")
print(normalized_df)
# Ранжирование: мин-макс шкала
ranked_df = (df - df.min()) / (df.max() - df.min())

# Вывод ранжированного DataFrame
print("\nРанжированный DataFrame:")
print(ranked_df)


Нормализованный DataFrame:
        0       1       2       3       4       5       6       7       8  \
0  0.0761  0.2152  0.1465  0.4552  1.9329 -0.6615 -0.0497  0.2601 -0.1086   
1  0.4603 -1.8724  1.4563  1.3454 -0.2383  0.1060 -0.3558  0.2167  0.3257   
2 -2.0695  0.1785 -0.9910  0.3743  0.6090 -0.8230 -1.0904  0.2167 -1.4903   
3  1.0688  1.1308  0.5257 -0.5564 -0.2913 -0.9442 -0.1416  0.2167  0.5231   
4  0.2042  0.0687 -1.4391 -1.5679 -0.9797  1.7218  1.3276  0.2167  0.0888   
5 -0.7566 -0.9568  0.0086 -0.1517 -0.3442 -0.8230 -1.4883 -0.4334  1.8653   
6  0.8446  0.1419  1.0082 -0.9610 -1.1915  1.1159  0.7155  1.4303 -0.3060   
7  0.1721  1.0941 -0.7152  1.0621  0.5031  0.3080  1.0828 -2.1238 -0.8981   

        9  
0  0.3106  
1  1.3140  
2 -1.7918  
3  0.6928  
4 -0.3106  
5  0.3584  
6 -1.0273  
7  0.4539  

Ранжированный DataFrame:
       0      1      2      3      4      5      6      7      8      9
0 0.6837 0.6951 0.5476 0.6944 1.0000 0.1061 0.5109 0.6707 0.4118 0.6769
1

## Упражнение № 64

Вычислите корреляцию каждой строки `df` с последующей строкой.

In [ ]:
import pandas as pd
import numpy as np

# Пример DataFrame
df = pd.DataFrame(np.random.randint(1, 100, 80).reshape(8, -1))
print(df)
# Вычисление корреляции каждой строки с последующей
correlation_with_next_row = df.corrwith(df.shift(-1, axis=0), axis=1)

# Вывод результатов
print("Корреляция с последующей строкой:")
print(correlation_with_next_row)


    0   1   2   3   4   5   6   7   8   9
0  18  38  47  76  14  96  58  74  13  86
1  66   3  39  22  92  98   8  14  90  12
2  84  31   3  68  11  98  51  15  21  59
3  56  41  11  36  83  64  11  31  42  27
4  87  60  83  55  14  53  49  56  92  27
5  67  66  70   7  66  36  37  73  48  15
6  89  40   6  21  75  37  29  33  42  98
7  90  22  52   3  77  20  21   6  20  12
Корреляция с последующей строкой:
0   -0.3655
1    0.1327
2    0.2112
3   -0.2950
4    0.2972
5   -0.0577
6    0.4170
7       NaN
dtype: float64


## Упражнение № 65

Замените все значения в обеих диагоналях `df` на 0.

In [ ]:
import pandas as pd
import numpy as np

# Пример DataFrame
df = pd.DataFrame(np.random.randint(1, 100, 100).reshape(10, -1))

# Замена значений в обеих диагоналях на 0
for i in range(len(df)):
    df.iloc[i, i] = 0
    df.iloc[i, len(df) - i - 1] = 0

# Вывод результата
print(df)


    0   1   2   3   4   5   6   7   8   9
0   0  71  36  19  64  89  73  90  86   0
1  30   0  52  93  42  33  31  27   0  35
2  45  39   0  70  59  42  83   0  13  31
3  24  92  68   0   7  37   0  75  50  71
4   1   8  30  64   0   0  56  45  87  34
5  65  73  35  39   0   0  66  40  70  45
6  74  80   8   0  60  33   0  39  13  17
7  87  66   0  10  31  16   1   0  12  55
8  81   0  15  67  14   5  34   1   0   9
9   0  76  85   9  44  94  72  93  14   0


## Упражнение № 66

Из `df_grouped` получите в виде датафрейма группу, относящуюся к `apple`.

In [ ]:
import pandas as pd
import numpy as np

# Пример DataFrame
df = pd.DataFrame({'col1': ['apple', 'banana', 'orange'] * 3,
                   'col2': np.random.rand(9),
                   'col3': np.random.randint(0, 15, 9)})
print(df)
# Группировка по 'col1'
df_grouped = df.groupby(['col1'])

# Получение группы 'apple'
apple_group = df_grouped.get_group('apple')

# Вывод результата
print(apple_group)


     col1   col2  col3
0   apple 0.7426    13
1  banana 0.1159    14
2  orange 0.6880    11
3   apple 0.6958     4
4  banana 0.2810    12
5  orange 0.5159     8
6   apple 0.4796    12
7  banana 0.4524     7
8  orange 0.7825     8
    col1   col2  col3
0  apple 0.7426    13
3  apple 0.6958     4
6  apple 0.4796    12


## Упражнение № 67

В `df` найдите второе по величине значение `taste` для `banana`.

In [ ]:
import pandas as pd
import numpy as np

# Пример DataFrame
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'rating': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})
print(df)
# Фильтрация данных для banana
banana_data = df[df['fruit'] == 'banana']

# Сортировка данных по убыванию значения 'rating'
sorted_banana_data = banana_data.sort_values(by='rating', ascending=False)

# Получение второго по величине значения 'rating'
second_largest_taste = sorted_banana_data.iloc[1]['rating']

# Вывод результата
print(second_largest_taste)


    fruit  rating  price
0   apple  0.9865     13
1  banana  0.6467      4
2  orange  0.6944      7
3   apple  0.6017     14
4  banana  0.6449      5
5  orange  0.6218      7
6   apple  0.7369      8
7  banana  0.4053      6
8  orange  0.0846      9
0.644865045611628


## Упражнение № 68

В `df` вычислите среднюю цену `Price` каждого фрукта `Fruit`, сохраняя фрукт как еще один столбец вместо индекса.

In [ ]:
# Пример DataFrame
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'rating': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})
print(df)
# Группировка по столбцу 'fruit' и вычисление среднего значения для 'price'
result_df = df.groupby('fruit', as_index=False)['price'].mean()

# Вывод результата
print(result_df)


    fruit  rating  price
0   apple  0.4766      6
1  banana  0.8153      8
2  orange  0.0699      0
3   apple  0.8201      2
4  banana  0.0486     10
5  orange  0.7455      6
6   apple  0.2728     13
7  banana  0.0747      6
8  orange  0.7007      3
    fruit  price
0   apple 7.0000
1  banana 8.0000
2  orange 3.0000


## Упражнение № 69

Объединить датафреймы `df1` и `df2` по признакам `fruit-pazham` и `weight-kilo`.

In [ ]:
# Примеры DataFrame
df1 = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                    'weight': ['high', 'medium', 'low'] * 3,
                    'price': np.random.randint(0, 15, 9)})

df2 = pd.DataFrame({'pazham': ['apple', 'orange', 'pine'] * 2,
                    'kilo': ['high', 'low'] * 3,
                    'price': np.random.randint(0, 15, 6)})
print(df1)
print(df2)
# Объединение по признакам 'fruit-pazham' и 'weight-kilo'
result_df = pd.merge(df1, df2, left_on=['fruit', 'weight'], right_on=['pazham', 'kilo'], how='inner')

# Удаление лишних столбцов
result_df = result_df.drop(['pazham', 'kilo'], axis=1)

# Вывод результата
print(result_df)


    fruit  weight  price
0   apple    high      8
1  banana  medium      0
2  orange     low      9
3   apple    high      2
4  banana  medium     10
5  orange     low      7
6   apple    high      5
7  banana  medium     13
8  orange     low      1
   pazham  kilo  price
0   apple  high     14
1  orange   low      8
2    pine  high     12
3   apple   low     14
4  orange  high      3
5    pine   low      9
    fruit weight  price_x  price_y
0   apple   high        8       14
1   apple   high        2       14
2   apple   high        5       14
3  orange    low        9        8
4  orange    low        7        8
5  orange    low        1        8


## Упражнение № 70

Создайте в `df` два новых столбца, один из них — `lag1` (сдвиг столбца `a` вниз на 1 строку) столбца 'a', а другой — `lead1` (сдвиг столбца `b` вверх на 1 строку).

In [ ]:
# Пример DataFrame
df = pd.DataFrame(np.random.randint(1, 100, 20).reshape(-1, 4), columns=list('abcd'))

# Создание столбцов lag1 и lead1
df['a_lag1'] = df['a'].shift(1)
df['b_lead1'] = df['b'].shift(-1)

# Вывод результата
print(df)


    a   b   c   d  a_lag1  b_lead1
0  47  72  75  21     NaN  94.0000
1  93  94  79  70 47.0000  75.0000
2  75  75  71  86 93.0000  69.0000
3  36  69  87  25 75.0000  82.0000
4  63  82  82  97 36.0000      NaN


## Упражнение № 71

Получите частоты уникальных значений по всему датафрейму `df`.

In [ ]:
# Пример DataFrame
df = pd.DataFrame(np.random.randint(1, 10, 20).reshape(-1, 4), columns=list('abcd'))
print(df)
# Получение частот уникальных значений по всему датафрейму
value_counts = df.stack().value_counts()

# Вывод результата
print(value_counts)


   a  b  c  d
0  3  1  1  2
1  3  2  8  9
2  2  1  9  1
3  7  7  3  7
4  7  1  1  3
1    6
3    4
7    4
2    3
9    2
8    1
Name: count, dtype: int64


## Упражнение № 72

Разделите столбец `row` в `df` так, чтобы сформировать датафрейм с 3 столбцами, как показано в примере выходных данных. 